islandora_solr_metadata.settings:
  type: config_object
  label: Settings
  mapping:
    islandora_solr_metadata_omit_empty_values:
      type: boolean
    islandora_solr_metadata_dedup_values:
      type: boolean
    islandora_solr_metadata_field_value_separator:
      type: string
islandora_solr_metadata.configs:
  type: config_object
  label: Metadata Configurations
  mapping:
    configs:
      type: sequence
      label: Metadata Configurations
      sequence:
        type: islandora_solr_metadata.config
