islandora_solr_metadata.settings:
  type: mapping
  label: Settings
  mapping:
    islandora_solr_metadata_omit_empty_values:
      type: boolean
    islandora_solr_metadata_dedup_values:
      type: boolean
    islandora_solr_metadata_field_value_separator:
      type: string
